### ISSUE TITLE
elfeed-tube-add-feeds doesn't work with handle-based channel urls

### ISSUE THREAD

**Issue by d-us-vb** [karthink/elfeed-tube#13]
If I try to run `elfeed-tube-add-feeds` for a channel like `https://www.youtube.com/@Bisqwit`, it always fails.

Looking at the source for `elfeed-tube-add-feeds`, it looks like the way it checks whether or not an input is a channel is by using the original channel URL format: `https://youtube.com/channel/base-64-id`. It is tedious to find the channel's base-64 id now. It requires hunting through the channel's page source for it.

Could this function be updated to add a channel automatically given the new URL format?

**Comment by karthink** [comment]
You can just search for `bisqwit` and `elfeed-tube-add-feeds` finds the channel. I'll look into adding support for `@`channels.

**Comment by karthink** [comment]
Added support for handle-based channel urls.
