### ISSUE TITLE
Add support for refile to elfeed-org file in elfeed-tube-channels-mode (potentially out of scope)

### ISSUE THREAD

**Issue by ParetoOptimalDev** [karthink/elfeed-tube#17]
It might be that `elfeed-tube-org` needs to be made to provide `elfeed-tube-add-feeds`.

Or this might be simple enough since you can just format data a bit, call org-refile with `rmh-elfeed-org-files` as a target, then be done.

I might end up implementing it myself honestly after describing the above :smile:

**Comment by karthink** [comment]
Sure, you can write a defun that accesses the variable `tabulated-list-entries` (which contains the channel feed data in the channels buffer) and does the refiling, say `elfeed-tube-add--refile`.  Then you can bind it to a key in `elfeed-tube-channels-mode-map` and you're set.

**Comment by stottm** [comment]
Elisp newbie here.  Does this refer to the way elfeed-tube-add-feeds adds feeds directly to the elfeed-db while not updating the elfeed.org list of feeds and tags?  I realize elfeed-org is an entirely different package but it's quite popular.  

I would vote to either add the functionality to elfeed-tube or document some DIY examples on how to capture the feed data to write an entry to the elfeed.org feed list.

**Comment by karthink** [comment]
> Elisp newbie here.  Does this refer to the way elfeed-tube-add-feeds adds feeds directly to the elfeed-db while not updating the elfeed.org list of feeds and tags?  I realize elfeed-org is an entirely different package but it's quite popular.

Yes, that's the desired feature.
  
> I would vote to either add the functionality to elfeed-tube or document some DIY examples on how to capture the feed data to write an entry to the elfeed.org feed list.  

If someone wants to add this functionality to elfeed-tube, I'm happy to accept a PR.  I explained above how you could do it.

You can already capture the feed data: See the demo video in the readme: https://github.com/karthink/elfeed-tube#step-i-add-youtube-subscriptions-to-elfeed

The window with the feeds lists an option to copy the feed urls as a list.
