### ISSUE TITLE
Invidious is unstable

### ISSUE THREAD

**Issue by xbc5** [karthink/elfeed-tube#21]
Timeouts occur often. Do we use invidious for:
1. video data;
2. other features (e.g. closed captions)?

If 1: could we put invidious behind a feature toggle? [MPV supports direct YT links via YT-DLP](https://wiki.archlinux.org/title/Mpv#Twitch.tv_streaming_over_mpv).

Another good addition would be a scoring system: the [API has a monitor field](https://api.invidious.io/instances.json?pretty=1&sort_by=type,users) that we could easily map, reduce, and sort at boot.

**Could you clarify what purpose invidious serves within this package?**

Thanks.

**Comment by karthink** [comment]
Invidious is used to get all video metadata except the transcripts. This includes the thumbnail, duration and video description.

> Timeouts occur often. 

If timeouts occur, elfeed-tube should automatically switch to a different Invidious instance and retry. Multiple Invidous instances would have to be down simultaneously before there's a failure in fetching metadata.

> could we put invidious behind a feature toggle? MPV supports direct YT links via YT-DLP

Invidious and mpv (as used by elfeed-tube) are not connected in any way. I'm not sure what you mean here.

> the [API has a monitor field](https://api.invidious.io/instances.json?pretty=1&sort_by=type,users) that we could easily map, reduce, and sort at boot.

Yup, this could be done. If you would like to submit a PR, please go ahead. You could start by looking at the functions `elfeed-tube--get-invidious-servers` and `elfeed-tube--nrotate-invidious-servers`.

**Comment by xbc5** [comment]
> Invidious and mpv (as used by elfeed-tube) are not connected in any way. I'm not sure what you mean here.

I mean `elfeed-tube-mpv` fails to launch MPV if the invidious instance times out -- no feedback (except the log buffer).

> Yup, this could be done. If you would like to submit a PR, please go ahead...

I probably will, but not immediately.
