### ISSUE TITLE
Incorrect MPV URL when using `elfeed-tube-mpv`

### ISSUE THREAD

**Issue by xbc5** [karthink/elfeed-tube#22]
When I use `elfeed-tube-mpv` on an elfeed filter entry, It launches MPV with `https://www.youtube.com/watch?v=<<id>>&t0` -- for some reason this doesn't work.

I launch this manually via MPV and it breaks. However, YT-DLP will work just fine.

I opened this issue initially because I thought it was an elfeed issue, but now I am thinking it's an issue with my installation.

Can someone try this and see if it works: `mpv 'https://www.youtube.com/watch?v=dQw4w9WgXcQ&t=0'`.

**Comment by karthink** [comment]
`dQw4w...`: As a policy I don't open URLs that begin with this string. (Learned from experience.)

I can confirm that `&t=0` works in general with mpv, though.

**Comment by xbc5** [comment]
It must be my system then. It's weird because it rejects `t=0` but not `x=0`.
