### ISSUE TITLE
Transcripts have moved to the description

### ISSUE THREAD

**Issue by sjLambda** [karthink/elfeed-tube#24]
For youtube videos whose "transcripts have moved to the description", the M-x elfeed-tube-fetch does not get the transcript. Is this a known issue or something new? Workaround? Suggestions? 

"Transcripts have moved to the description" is youtube message when you click on Show Transcript for the video. M-x elfeed-tube-fetch does not get fetch transcripts for such videos.

**Comment by karthink** [comment]
Could you give me an example?

**Comment by sjLambda** [comment]
﻿﻿https://youtu.be/ZGxm7zfN768

Now this example works. It did not when I first tried. After several tries, I posted the issue. Now it works on both my machines. Unless you have any advice, you can close the issue. Thanks.

**Comment by karthink** [comment]
Let's open the issue if it crops up again.
