### ISSUE TITLE
elfeed-tube-mpv only accepts youtube links

### ISSUE THREAD

**Issue by AManNeedsAMaid** [karthink/elfeed-tube#30]
Hello,

I'm aware that this project is focused on watching / getting info about youtube videos in elfeed, however I have a few feeds from sites like Odysee or Peertube in my RSS. These sites work fine when being played via mpv, however the elfeed-tube-mpv function does nothing, presumably because it checks if the url is specifically a youtube link. 

I understand a use case where sending mpv an unplayable url on accident wouldn't be ideal, but could there be a variable added to allow indiscriminate passing of links to mpv? This would make the functionality much more versatile imo. 

EDIT: Upon further inspection, I believe the function relies on a video id being present. A variable that would simply make the alternative to a video id being present passing the entry's url to elfeed as 'video-url' would be much appreciated

**Comment by karthink** [comment]
The problem is not that non-youtube links are explicitly disallowed.  There needs to be integration with the Odysee and Peertube APIs (if available) to retrieve the relevant metadata like descriptions, duration and transcripts.  This does not exist in elfeed-tube.  PRs are welcome.

**Comment by karthink** [comment]
> but could there be a variable added to allow indiscriminate passing of links to mpv?

I think I misunderstood your question.  If all you want to do is play your Elfeed entry links in mpv, you don't even need elfeed-tube.

See [this comment](https://github.com/karthink/elfeed-tube/issues/15#issuecomment-1471011109) in #15.

**Comment by AManNeedsAMaid** [comment]
> > but could there be a variable added to allow indiscriminate passing of links to mpv?
> 
> I think I misunderstood your question. If all you want to do is play your Elfeed entry links in mpv, you don't even need elfeed-tube. Elfeed-tube is only required if you want to fetch additional metadata about the videos.
> 
> See [this comment](https://github.com/karthink/elfeed-tube/issues/15#issuecomment-1471011109) in #15.

Thank you, that's _exactly_ what I wanted, appreciate the clean solution, closed.
