### ISSUE TITLE
Title: C-c C-c etc dont work in results buffer

### ISSUE THREAD

**Issue by tvraman** [karthink/elfeed-tube#6]
Description:

Called  elfeed-tube-add-feeds successfully and it appeared to find the
feed, see results buffer below.

However none of the listed keys in that buffer e.g. c-c c-c, c-c c-w
etc work:
Emacs claims those keys are undefined in that buffer.

--------------------------------------------------
Pen  Bhakti            watch?v=dnloFi1GT9Q&list=PLa6CHPhFNfadNcnVZRXa6csHL5sFdkwmV&index=3 https://www.youtube.com/feeds/videos.xml?channel_id=UCHKGDg0GJKBsA9mFraDOLHA

All queries resolved successfully.

     C-c C-c: Add all feeds to the Elfeed database.
 C-u C-c C-c: Add all feeds, fetch entries from them and open Elfeed.
     C-c C-w: Copy the list of feed URLs as a list

q or C-c C-k: Quit and cancel this operation.

**Comment by karthink** [comment]
Oops, thanks for catching that. Should be fixed in a048950.

**Comment by karthink** [comment]
Is the keymap populated correctly for you now?

**Comment by tvraman** [comment]
will try it soon, has the fix gone out to melpa?


-- 

Thanks,

--Raman(I Search, I Find, I Misplace, I Research)
♈ Id: kg:/m/0285kf1  🦮

**Comment by karthink** [comment]
Yes, the MELPA version is the latest.
