### ISSUE TITLE
error when running elfeed-tube-fill-feeds

### ISSUE THREAD

**Issue by emacsbliss** [karthink/elfeed-tube#8]
got this error when running `elfeed-tube-fill-feeds` with latest commit:
```
 execute-extended-command: Autoloading file ~/.emacs.d/straight/build/elfeed-tube-mpv/elfeed-tube-utils.elc failed to define function elfeed-tube-fill-feeds
```

**Comment by karthink** [comment]
> got this error when running `elfeed-tube-fill-feeds` with latest commit:

Oops. Should be fixed now. Depending on how you installed it, you may need to reinstall or rebuild the package for the autoloads to be regenerated correctly.

**Comment by emacsbliss** [comment]
Thanks a lot for the prompt fix!

It works now.

however I'm not sure if I didn't use it properly, I added the feeds from this youtube video:

https://www.youtube.com/watch?v=l1mER1bV0N0

then I did the backfill for this feeds. 

After that I couldn't find this video from all the feeds, any ideas?

**Comment by karthink** [comment]
> https://www.youtube.com/watch?v=l1mER1bV0N0
>
> After that I couldn't find this video from all the feeds, any ideas?

It's going to be all or nothing, I don't think it can fail to add one video. Did it add any of the older videos?

**Comment by emacsbliss** [comment]
it does fetch some older videos, just can't find this one.. anyway, I can just get this video alone.

Thanks again for the help!

**Comment by karthink** [comment]
I just added this feed and filled it, and it added 464 missing video entries, including the one dated 2020-07-07 that you said was missing.

Can you check if it's an issue with your elfeed search filter? The newly fetched entries for this feed may not have had the same tags applied as your pre-existing ones.
