### ISSUE TITLE
[feature request] import srt for local video

### ISSUE THREAD

**Issue by emacsbliss** [karthink/elfeed-tube#9]
I'm thinking it could be helpful if it support import srt into it, then that open the possibility to use elfeed-tube for local videos (which has srt)..

**Comment by karthink** [comment]
> I'm thinking it could be helpful if it support import srt into it, then that open the possibility to use elfeed-tube for local videos (which has srt)..

I didn't understand, what do you mean by "it" above? Are you suggesting adding a subtitle import feature to Elfeed Tube? But your disk-local videos aren't available as RSS feeds to begin with.

Or do you mean adding the ability to follow along to mpv (playing a local video) in a subtitle buffer? Elfeed would be unnecessary for this.

**Comment by emacsbliss** [comment]
> I'm thinking it could be helpful if it support import srt into it, then that open the possibility to use elfeed-tube for local videos (which has srt)..
> I didn't understand, what do you mean by "it" above? Are you suggesting adding a subtitle import feature to Elfeed Tube? But your disk-local videos aren't available as RSS feeds to begin with. Or do you mean adding the ability to follow along to mpv (playing a local video) in a subtitle buffer? Elfeed would be unnecessary for this.

Sorry for not being clear, I'm refer to the first case you mentioned. But then I realize I forgot local video is not rss, so let's drop it for now
